# Generated by Django 3.2.6 on 2021-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Sub_Questions', models.TextField(blank=True, null=True)),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Link', models.URLField(blank=True, null=True)),
                ('Tag', models.CharField(choices=[('Python', ((1, 'List'), (2, 'Tuple'), (3, 'Dictionary'), (4, 'Set'), (5, 'OOPS')))], default='Python', max_length=30)),
            ],
        ),
    ]
