# Generated by Django 3.2.6 on 2021-12-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programmes', '0002_alter_programms_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='programms',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programms',
            name='Tag',
            field=models.CharField(choices=[('Python', (('List', 'List'), ('Dictionary', 'Dictionary'), ('Tuple', 'Tuple'), ('Set', 'Set'), ('OOPS', 'OOPS'), ('Data Base', 'Data Base'), ('File handling', 'File handling'), ('Genral', 'Genral'))), ('Django', (('Middle ware', 'Middle ware'), ('Session', 'Session'), ('cookies', 'cookies'))), ('Flask', (('Decorators', 'Decorators'), ('App.run()', 'App.run()'))), ('Rest Api', (('JSON', 'JSON'), ('Mixin', 'Mixin'))), ('AWS', (('Lambda', 'Lambda'), ('Boto 3', 'Boto 3')))], default='Python', max_length=30),
        ),
    ]
